FROM mysql:5.7.26

RUN apt update && apt install -y procps lsof
RUN sed -i 's|#bind-address.*$|bind-address = 0.0.0.0|g' /etc/mysql/mysql.conf.d/mysqld.cnf

RUN echo 'touch /tmp/test' >> /docker-entrypoint-initdb.d/001-test.sh
RUN chmod 775 /docker-entrypoint-initdb.d/001-test.sh

RUN echo 'use my-app; create table test (name varchar(255));' >> /docker-entrypoint-initdb.d/001-test.sql
